# Generated by Django 5.0.3 on 2024-03-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_remove_user_room_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
