# Generated by Django 5.0.3 on 2024-03-07 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=15)),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memo.room')),
            ],
        ),
    ]
